# Generated by Django 2.0.3 on 2020-05-14 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfoods',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food', verbose_name='菜品'),
        ),
        migrations.AlterField(
            model_name='orderfoods',
            name='food_num',
            field=models.IntegerField(default=0, verbose_name='菜品数量'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food', verbose_name='菜品'),
        ),
    ]
