# Generated by Django 2.0.3 on 2020-05-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20200528_1806'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='orderinfo',
        #     name='signer_name',
        # ),
        # migrations.RemoveField(
        #     model_name='orderinfo',
        #     name='singer_mobile',
        # ),
        migrations.AlterField(
            model_name='orderinfo',
            name='post_script',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='订单留言'),
        ),
    ]
