# Generated by Django 2.0.3 on 2020-06-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20200531_1137'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='orderinfo',
        #     name='signer_name',
        # ),
        # migrations.RemoveField(
        #     model_name='orderinfo',
        #     name='singer_mobile',
        # ),
        migrations.AddField(
            model_name='orderinfo',
            name='comment_status',
            field=models.BooleanField(default=False, verbose_name='是否评论'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='orderinfo_status',
            field=models.CharField(default='待支付', max_length=10, verbose_name='支付状态'),
        ),
    ]
