# Generated by Django 2.0.3 on 2020-06-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20200602_1957'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='orderinfo',
        #     name='signer_name',
        # ),
        # migrations.RemoveField(
        #     model_name='orderinfo',
        #     name='singer_mobile',
        # ),
        migrations.AlterField(
            model_name='orderinfo',
            name='orderinfo_status',
            field=models.IntegerField(default='-8', verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', '成功'), ('TRADE_CLOSED', '超时关闭'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_FINISHED', '交易结束'), ('PAYING', '待支付')], default='paying', max_length=30, verbose_name='支付状态'),
        ),
    ]
