# Generated by Django 2.0.3 on 2020-05-16 12:46

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200516_2046'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100, verbose_name='评论内容')),
                ('comment_type', models.CharField(choices=[('praise', '好评'), ('mid-review', '中评'), ('bad', '差评')], default='praise', max_length=10, verbose_name='评论等级')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.AlterField(
            model_name='food',
            name='summary',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='介绍'),
        ),
        migrations.AddField(
            model_name='foodcomment',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodcomment', to='food.Food', verbose_name='菜品名'),
        ),
        migrations.AddField(
            model_name='foodcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercomment', to='users.UserInfo', verbose_name='用户评论'),
        ),
    ]
