# Generated by Django 2.0.3 on 2020-05-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200528_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='yun_price',
            field=models.FloatField(default=0.0, verbose_name='运费'),
        ),
    ]
