# Generated by Django 2.0.3 on 2020-04-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('nickname', models.CharField(max_length=64, verbose_name='昵称')),
                ('avatar', models.CharField(blank=True, max_length=64, null=True, verbose_name='头像')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户Token')),
            ],
        ),
    ]
