# Generated by Django 2.0.3 on 2020-05-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='area_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='地区id'),
        ),
        migrations.AddField(
            model_name='address',
            name='area_str',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='address',
            name='city_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='城市id'),
        ),
        migrations.AddField(
            model_name='address',
            name='city_str',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='address',
            name='province_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='省份id'),
        ),
        migrations.AddField(
            model_name='address',
            name='province_str',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='详细地址'),
        ),
    ]
