# Generated by Django 2.0.3 on 2020-06-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_address_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': '用户地址', 'verbose_name_plural': '用户地址'},
        ),
    ]
